### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by Victoremepunto**
- Restructures project to add basic config files
- Adds pre-commit
- Adds Github action for pre-commit
- Adds Github GPG public key to the list of known keys

### CODE REVIEW

**Comment by adamrdrew** [comment]
This LGTM - but I am not familiar with this project so you may want another opinion. This looks mostly like a reorganization with some additional integration and config stuff. Looking through the logic it doesn't look like muhc at all changed - just moved around and cleaned up. If this were my repo I'd be comfortable merging this.

**Comment by Victoremepunto** [comment]
> This LGTM - but I am not familiar with this project so you may want another opinion. This looks mostly like a reorganization with some additional integration and config stuff. Looking through the logic it doesn't look like muhc at all changed - just moved around and cleaned up. If this were my repo I'd be comfortable merging this.

Thanks for the review ! actually (arguably) the most important bit is https://github.com/RedHatInsights/gpg-verify/pull/4/commits/17c5c279be8aa155c94615d27a2cd34fd89fc372 as is what triggered this PR - I added the refactor and minimal config files as I felt them needed as a bare minimum.

**Comment by adamrdrew** [comment]
Ah thanks for the clarification. That makes sense, adding the github user. Should you have any error handling around this? I mean, I bet its going to be fine. But, in case github were to be having a service interruption while grabbing the key? Just a thought - likely not critical.

**Comment by Victoremepunto** [comment]
> Ah thanks for the clarification. That makes sense, adding the github user. Should you have any error handling around this? I mean, I bet its going to be fine. But, in case github were to be having a service interruption while grabbing the key? Just a thought - likely not critical.

Actually it's a good point, and the thought I had around it was - I was considering committing the key itself into the repo, so I don't have to fetch it every time (for every run) - WDYT ? that removes the `requests` dependency . we'll have to update the GPG signing key if that "ever" changes but that's it .

**Comment by Victoremepunto** [comment]
> > Ah thanks for the clarification. That makes sense, adding the github user. Should you have any error handling around this? I mean, I bet its going to be fine. But, in case github were to be having a service interruption while grabbing the key? Just a thought - likely not critical.
> 
> Actually it's a good point, and the thought I had around it was - I was considering committing the key itself into the repo, so I don't have to fetch it every time (for every run) - WDYT ? that removes the `requests` dependency . we'll have to update the GPG signing key if that "ever" changes but that's it .

@adamrdrew  I actually went ahead and commit it to the repo as the likeness of the GPG pub key changes tends to 0 - and that removes the `requests` dependency.

**Pull request merged**
